name: Release

on:
  push:
    branches:
      - master

permissions: {}

jobs:
  release:
    name: Publish & Deploy
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          fetch-depth: 0
          token: ${{ secrets.SEEK_OSS_CI_GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: package.json

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Publish action
        id: changesets
        uses: changesets/action@a45c4d594aa4e2c509dc14a9f2b3b67ba3780d0d # v1
        with:
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.SEEK_OSS_CI_GITHUB_TOKEN }}
